Testing part 2
chimwemwe007/To-do-List pull request #5
Opened 2022-07-15 20:45 UTC by rmjspecial

**Project Description**

- created a function for editing the task description.
- Add a jest library.
- Add mock to update local storage

2022-07-15 21:41 UTC, gtekle requested changes
Hi @chimwemwe007 :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-01](https://user-images.githubusercontent.com/44057863/179314599-aa6c5ef6-61e7-4745-ba0e-cb9d05f2d797.gif)

## Highlights
:heavy_check_mark: Professional ReadMe
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Descriptive PR title and summary

## Required Changes ♻️
_Check the comments under the review._

- [ ] You are directly accessing the localStoarge in your test. Thus, kindly mock the localStorage   as it is this milestone's requirement and mocking external application makes your tests to run faster.
![image](https://user-images.githubusercontent.com/44057863/179314516-f8b2bd9a-7e1b-41bc-96db-19aebb28b046.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 21:41 UTC, gtekle commented on src/services.js
> +}
- [ ] Kindly add unit test for this function as it is part of this milestone's requirements. 
![image](https://user-images.githubusercontent.com/44057863/179314426-e07aa7b1-271b-4c83-82fe-3835f7377590.png)

2022-07-15 21:41 UTC, gtekle commented on src/update_complete.js
> +}
- [ ] Kindly add unit test for this function as it is part of this milestone's requirements.
![image](https://user-images.githubusercontent.com/44057863/179314374-6289ca01-4fd4-4814-b2e7-02c8da17bd66.png)

2022-07-15 21:41 UTC, gtekle commented on src/update_complete.js
> +}
- [ ] Kindly add unit test for this function as it is part of this milestone's requirements.
![image](https://user-images.githubusercontent.com/44057863/179314354-32f31486-4621-4e6d-8062-7af924672bcd.png)

2022-07-16 09:13 UTC, gtekle commented
Hi @chimwemwe007 
As per our discussion over slack, since you are using a Jest version 28.1.3 you can disregard my previous suggestion to mock localStorage.

Happy coding 👍

2022-07-16 18:17 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @rmjspecial  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 19:15 UTC, merged